sonar.projectKey=tasklist-frontend
sonar.projectName=TaskList Frontend
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,src/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
